In [1]:
import numpy as np

In [53]:
a = np.array(np.ones([5, 3]))
ind = np.random.choice(a.shape[0], 2)
print a

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [56]:
b = np.array([1,2,3,4,5])
print b
print 1-b
print a
print a*b[:, np.newaxis]

[1 2 3 4 5]
[ 0 -1 -2 -3 -4]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]]


In [60]:
c=5
c/=float(2)
print c

2.5


In [61]:
d = np.array([1,2,3])
d**2

array([1, 4, 9])

In [88]:
e = np.array(np.zeros([5]))
np.hstack((e, 5))

array([ 0.,  0.,  0.,  0.,  0.,  5.])

In [163]:
from scipy import sparse
X = np.array(np.zeros([8, 5]))
X[2, 3] = 1
X[3, 4] = 2
X = sparse.csr_matrix(X)
X = sparse.hstack((X, np.ones(X.shape[0])[:, np.newaxis])).tocsr()

In [168]:
X.toarray()

array([[ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [140]:
Y = sparse.csr_matrix(np.array([[0,3,5],[4,0,0],[0,5,0],[0,0,0],[1,2,3]]))
print Y.indices
print Y.data
print "="*10
Z = np.array([6,7,8])
print Y.toarray()
Y.data  *= Z[Y.indices]
print Y.toarray()

[1 2 0 1 0 1 2]
[3 5 4 5 1 2 3]
[[0 3 5]
 [4 0 0]
 [0 5 0]
 [0 0 0]
 [1 2 3]]
[[ 0 21 40]
 [24  0  0]
 [ 0 35  0]
 [ 0  0  0]
 [ 6 14 24]]


In [196]:
def loss(X_batch, y_batch, reg, w):
        """Logistic Regression loss function
        Inputs:
        - X: N x D array of data. Data are D-dimensional rows
        - y: 1-dimensional array of length N with labels 0-1, for 2 classes
        Returns:
        a tuple of:
        - loss as single float
        - gradient with respect to weights w; an array of same shape as w
        """
        dw = np.zeros_like(w)  # initialize the gradient as zero
        loss = 0
        # Compute loss and gradient. Your code should not contain python loops.
        sigma = lambda z: 1/(1+np.exp(-z))
        
        M = y_batch*X_batch.dot(w)
        
        loss = np.sum(np.log(1+np.exp(-M)))
        
        X = X_batch.copy()
        X.data *= (sigma(-M)*y_batch)[X.indices]
        dw = X.sum(axis=0)
        
        print X.toarray()
        print dw
        # Right now the loss is a sum over all training examples, but we want it
        # to be an average instead so we divide by num_train.
        # Note that the same thing must be done with gradient.
        loss /= float(X_batch.shape[0])
        dw /= float(X_batch.shape[0])
        # Add regularization to the loss and gradient.
        # Note that you have to exclude bias term in regularization.
        loss += np.sum(reg*w[:-1]**2)
        dw += 2*reg*np.hstack((w[:-1], 0))

        return loss, np.array(dw.T)

X = np.vstack((np.ones([50, 1]), -np.ones([50, 1])))
X = np.hstack((np.random.randn(100, 1), X))

X = sparse.csr_matrix(X)
w = np.random.randn(X.shape[1]+1) * 2
y = np.hstack((np.zeros(50),np.ones(50)))

X = sparse.hstack((X, np.ones(X.shape[0])[:, np.newaxis])).tocsr()

print w
print X.shape
print y.shape
loss, grad = loss(X, y, 0.5, w)


[ 2.94309325 -0.77640517  0.92104593]
(100, 3)
(100L,)
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]


In [230]:
X = sparse.csr_matrix([[1,1,0,1,0,0,0],[1,1,0,1,0,0,0]])
X = X.tocsc()
z = np.array([5,6,7,4,5,6,7])
X.data *= z[X.indices] 
print X.toarray()

[[5 5 0 5 0 0 0]
 [6 6 0 6 0 0 0]]


In [ ]:
a=np.random.randn(1,2)